extends: airbnb-base
plugins:
  - import
installedESLint: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
env:
  node: true
  es6: true
rules:
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: only-multiline
      exports: only-multiline
      functions: ignore
  max-len:
    - "error"
    - 80
  import/no-extraneous-dependencies:
    - "error"
    - devDependencies: true
      optionalDependencies: true
      peerDependencies: true
  no-param-reassign:
    - "error"
    - props: true
      ignorePropertyModificationsFor:
        - "scope"
