extends: airbnb-base
plugins:
  - import
installedESLint: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
env:
  node: true
  es6: true
rules:
  import/no-extraneous-dependencies:
    - "error"
    - devDependencies: true
      optionalDependencies: true
      peerDependencies: true
