language: node_js
sudo: false
compiler: g++-4.8
env:
  - CXX=g++-4.8
node_js:
  - "6.2"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
    packages:
      - g++-4.8
      - libnotify-bin
      - python3.5
      - python3.5-dev
      - python3.5-venv
cache:
  apt: true
  pip: true
  directories:
    - "${HOME}/.npm"
    - "node_modules"
    - "app/static"
before_script:
  - "npm update"
  - "pyvenv-3.5 ../venv"
  - "source ../venv/bin/activate && pip install -r requirements.txt && deactivate"
script:
  - "source ../venv/bin/activate && echo ${VIRTUAL_ENV} && npm test && deactivate"
