sudo: false
language: node_js
node_js:
  - "6.1"
python:
  - "3.5"
cache:
  pip: true
  directories:
    - node_modules
    - app/static
before_install:
  - pip install -r requirements.txt
script:
  - npm test
