language: python
python:
  - "3.5"
cache:
  apt: true
  pip: true
  directories:
    - "${HOME}/.npm"
    - "node_modules"
addons:
  apt:
    sources:
      - sourceline: "deb-src https://deb.nodesource.com/node_6.x precise main"
        key_url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      - sourceline: "deb https://deb.nodesource.com/node_6.x precise main"
        key_url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    packages:
      - nodejs
before_script:
  - "npm install"
  - "npm run bower -- install"
script:
  - "npm test"
