language: node_js
sudo: false
cache:
  apt: true
  pip: true
  yarn: true
  directories:
    - "${HOME}/.npm"
    - "${HOME}/.nvm"
    - "node_modules"
    - "app/common/static/third_party"
    - "../venv"
compiler: g++-4.8
env:
  global:
    - CXX=g++-4.8
    - DEPLOY_REPO=https://hiroaki-yamamoto:${DEPLOY_KEY}@github.com/hysoftware/hysoftware.net-deploy.git
    - node_mode=production
node_js:
  - "node"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
    packages:
      - rsync
      - g++-4.8
      - libnotify-bin
      - python3.5
      - python3.5-dev
      - python3.5-venv
branches:
  except:
    - zappa
before_script:
  - "npm run update"
  - "pyvenv-3.5 ../venv"
  - "source ../venv/bin/activate"
  - "pip install -r requirements.txt"
  - "deactivate"
script:
  - "source ../venv/bin/activate"
  - "npm test"
  - "deactivate"
after_success:
  - "source ../venv/bin/activate"
  - "coveralls"
  - "codeclimate-test-reporter"
  - "deactivate"
before_deploy:
  - "./pack.sh"
  - "cd ${HOME}/deploy"
  - "git archive --format zip -o ${HOME}/deploy-${TRAVIS_BUILD_ID}.zip HEAD"
  - "cd ${TRAVIS_BUILD_DIR}"
deploy:
  - provider: releases
    api_key:
      secure: >-
        bURRx94lQUE4AslU82ztvCjZ9LhnS00dpjnX1ejiYiyHMLzHg/+efZCSZhLxmnpS2WXDUw
        7i2qzS0jQa1Rx+yFJrFCn8U3Cab5cLrEFPwzYFpUl0XZZa7uMwDQDqHLdxv9m2KH+LAgaW
        2u28e1yHtFozDWWi4qfkOkAF+HiSwgc=
    file: "${HOME}/deploy-${TRAVIS_BUILD_ID}.zip"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      tags: true
