language: node_js
sudo: false
cache:
  apt: true
  pip: true
  directories:
    - "${HOME}/.npm"
    - "node_modules"
    - "app/static"
compiler: g++-4.8
env:
  - CXX=g++-4.8
node_js:
  - "6.2"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
    packages:
      - g++-4.8
      - libnotify-bin
      - python3.5
      - python3.5-dev
      - python3.5-venv
install:
  - "npm install"
  - "npm update"
  - "npm run update"
  - "pyvenv-3.5 ../venv"
  - "source ../venv/bin/activate"
  - "pip install -r requirements.txt"
  - "deactivate"
script:
  - "source ../venv/bin/activate"
  - "npm test"
  - "deactivate"
after_success:
  - "source ../venv/bin/activate"
  - "coveralls"
  - "deactivate"
  - "npm run coveralls"
