uwsgi:
    http-socket: 127.0.0.1:50000
    http-socket: [::1]:50000
    plugins: python3
    chdir: ../../
    virtualenv: ../
    chmod: 666
    master: 4
    processes: 8
    env: DJANGO_SETTINGS_MODULE=hysoft.settings
    callable: application
    mount: /=hysoft/wsgi.py
    vacuum: ""
